name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs on an Ubuntu machine

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.6.6'  # Specify the version of Terraform you want

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: |
        cd aws-terraform  # Navigate to the directory where your Terraform files are
        terraform init -input=false

    # Step 4: Validate Terraform configuration
    - name: Terraform Validate
      run: |
        cd aws-terraform  # Ensure we're in the correct directory
        terraform validate

    # Step 5: Terraform Plan
    - name: Terraform Plan
      run: |
        cd aws-terraform  # Ensure we're in the correct directory
        #terraform plan -out=tfplan

    # Step 6: Upload Terraform Plan as an artifact
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: aws-terraform/tfplan

    # Step 7: Terraform Apply (only on main branch)
    - name: Terraform Apply
      run: |
        cd aws-terraform  # Ensure we're in the correct directory
        #terraform apply -input=false tfplan
      if: github.ref == 'refs/heads/main'  # Only apply changes on the main branch

  download_artifact:
    runs-on: ubuntu-latest
    needs: terraform  # This ensures that the artifact download runs after the terraform job
    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Download the Terraform Plan artifact
    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@v2
      with:
        name: tfplan  # Specify the artifact name that was uploaded
        path: ./downloaded-artifacts  # Path to store the downloaded artifact
